### ISSUE TITLE
 pre-trained model files are not found in the repository

### ISSUE THREAD

**Issue by GAgafencu** [bioinfomaticsCSU/LoopPredictor#1]
Dear Li Tang,

I would like to try the LoopPredictor tool, but I can't find the trained_model directory in the repository.
Consequently, I can't use the prediction feature of your tool using the models that that you devised.
Could you please indicate how I can access the .m and .fix files for the median model in order to test your tool?

Thank you for your time and help.

Grigore-Aristide Gafencu <grigore.gafencu@rdm.ox.ac.uk>

**Comment by bioinfomaticsCSU** [comment]
The link of trained_model directory has been updated on README.
